### ISSUE TITLE
Homepage - layout changes

### ISSUE THREAD

**Issue by briri** [cdlib/dmptool-ui#2]
Please see the annotated version of the homepage design that shows the order of the areas of the page for screen readers, mobile screens, etc. (its also a useful guide to how the grid column layout):
https://qvr42y.axshare.com/#id=tgdtad&p=home_hero-area_latest-news_right_structure&c=1

Changes:
- Replace the existing hero images with the ones in this [google drive folder](https://drive.google.com/drive/folders/1dhm7baaKZmv-GdQ8uKZ4xzrKsjAbG0oY) (except for image 'G'). You can also see examples of them with the call to action block on [this google doc](https://drive.google.com/file/d/1NNKus_FGPiZAbdRMUN4V7r7GWOtjiT-9/view?usp=sharing)
- The hero image should appear behind the call to action, not the sign in / create account block (this should prevent the image from resizing when you toggle back and forth from sign in and create account ... see [dmptool-stg](https://dmptool-stg.cdlib.org))
- Update the height width of the sign in image in this repo to match what we have out on dmptool-stg (350x655 for the create account tab and 350x533 for the sign in tab). We are open to widening this if it looks better and doesn't conflict with the call to action/hero image
- Pull the blog information and social media icons out of the footer and place them in a block next to the stats (see the annotated screenshot above)
- Update the footer to span the entire width of the page (see the annotated screenshot above)(note that the screenshot does not include the "Version: v3.4" info but we still want it to be there)

- [ ] Adjust font sizes and spacing see UX team code below
- [] Font loading issue on Windows 10 - Firefox

Font sizing and spacing changes:
```scss
// The following are the CSS modifications that I made to adjust the design. 
// There certainly may be better ways to achieve the same effects.

.c-home-stats__participants, .c-home-stats__plans, .c-home-stats__users {
  /* padding-top: 4.5rem; */
  /* font-weight: 700; */
  padding-top: 5rem;
  font-weight: 400;
}

.c-calltoaction {
  word-spacing: 0.25rem;
  line-height: 1.25;
}

```
